insert into cat_categoria (id, nombre) 
	values	(1, 'ABARROTES'),
			(2, 'PRODUCTOS ENLATADOS'),
			(3, 'LACTEOS'),
			(4, 'BOTANAS'),
			(5, 'DULCERIA'),
			(6, 'HARINAS Y PAN'),
			(7, 'FRUTAS Y VERDURAS'),
			(8, 'BEBIDAS'),
			(9, 'BEBIDAS ALCOHOLICAS'),
			(10, 'ALIMENTOS PREPARADOS'),
			(11, 'AUTOMEDICACION'),
			(12, 'HIGIENE PERSONAL'),
			(13, 'USO DOMESTICO'),
			(14, 'PRODUCTOS DE LIMPIEZA'),
			(15, 'OTROS PRODUCTOS');

insert into cat_producto (nombre,tipo_categoria) 
    values  (" Aceite comestibles",1),
            (" Aderezos",1),
            (" Consome",1),
            (" Crema de cacahuate",1),
            (" Crema para cafe",1),
            (" Pure de tomate",1),
            (" Alimento para bebe",1),
            (" Alimento para mascotas",1),
            (" Atole",1),
            (" Avena",1),
            (" Azucar",1),
            (" Cafe",1),
            (" Cereales",1),
            (" Chile piquin",1),
            (" Especias",1),
            (" Flan en polvo",1),
            (" Formulas infantiles",1),
            (" Gelatinas en polvo o Grenetina",1),
            (" Harina",1),
            (" Harina preparada",1),
            (" Mole",1),
            (" Sal",1),
            (" Salsas envasadas",1),
            (" Sazonadores",1),
            (" Sopas en sobre",1),
            (" Cajeta",1),
            (" Catsup",1),
            (" Mayonesa",1),
            (" Mermelada",1),
            (" Miel",1),
            (" Te",1),
            (" Vinagre",1),
            (" Huevo",1),
            (" Pastas",1),
            (" Aceitunas",2),
            (" Champiñones enteros o rebanados",2),
            (" Chicharo con zanahoria",2),
            (" Chicharos enlatados",2),
            (" Frijoles enlatados",2),
            (" Frutas en almibar",2),
            (" Sardinas",2),
            (" Atun en agua o aceite",2),
            (" Chiles enlatados",2),
            (" Chiles envasados",2),
            (" Ensaladas enlatadas",2),
            (" Granos de elote enlatados",2),
            (" Sopa en lata",2),
            (" Vegetales en conserva",2),
            (" Leche condensada",3),
            (" Leche deslactosada",3),
            (" Leche en polvo",3),
            (" Leche evaporada",3),
            (" Leche light",3),
            (" Leche pasteurizada",3),
            (" Leche saborizada",3),
            (" Leche semidescremada",3),
            (" Crema",3),
            (" Yoghurt",3),
            (" Mantequilla",3),
            (" Margarina",3),
            (" Media crema",3),
            (" Queso",3),
            (" Papas",4),
            (" Palomitas",4),
            (" Frituras de maiz",4),
            (" Cacahuates",4),
            (" Botanas saladas",4),
            (" Barras alimenticias",4),
            (" Nueces y semillas",4),
            (" Caramelos",5),
            (" Dulces enchilados",5),
            (" Chocolate de mesa",5),
            (" Chocolate en polvo",5),
            (" Chocolates",5),
            (" Gomas de mascar",5),
            (" Mazapan",5),
            (" Malvaviscos",5),
            (" Pulpa de tamarindo",5),
            (" Pastillas de dulce",5),
            (" Paletas de dulce",5),
            (" Tortillas de harina o maiz",6),
            (" Galletas dulces",6),
            (" Galletas saladas",6),
            (" Pastelillos",6),
            (" Pan de caja",6),
            (" Pan dulce",6),
            (" Pan molido",6),
            (" Pan tostado",6),
            (" Aguacates",7),
            (" Ajos",7),
            (" Cebollas",7),
            (" Chiles",7),
            (" Cilantro o Perejil",7),
            (" Jitomate",7),
            (" Papas",7),
            (" Limones",7),
            (" Manzanas",7),
            (" Naranjas",7),
            (" Platanos",7),
            (" Agua mineral",8),
            (" Agua natural",8),
            (" Agua saborizada",8),
            (" Jarabes",8),
            (" Jugos o Nectares",8),
            (" Naranjadas",8),
            (" Bebidas de soya",8),
            (" Bebidas en polvo",8),
            (" Bebidas infantiles",8),
            (" Bebidas isotonicas",8),
            (" Energetizantes",8),
            (" Isotonicos",8),
            (" Refrescos",8),
            (" Bebidas preparadas",9),
            (" Cerveza",9),
            (" Anis",9),
            (" Brandy",9),
            (" Ginebra",9),
            (" Cordiales",9),
            (" Mezcal",9),
            (" Jerez",9),
            (" Ron",9),
            (" Tequila",9),
            (" Sidra",9),
            (" Whiskey",9),
            (" Vodka",9),
            (" Pastas listas para comer",10),
            (" Sopas en vaso",10),
            (" Carnes y Embutidos",10),
            (" Salchicha",10),
            (" Mortadela",10),
            (" Tocino",10),
            (" Jamon",10),
            (" Manteca",10),
            (" Chorizo",10),
            (" Carne de puerco ",10),
            (" Carnde de res",10),
            (" Carne de pollo",10),
            (" Suero",11),
            (" Agua oxigenada",11),
            (" Preservativos",11),
            (" Alcohol",11),
            (" Gasas",11),
            (" Analgesicos",11),
            (" Antigripales",11),
            (" Antiacidos",11),
            (" Toallas humedas",12),
            (" Aceite para bebe",12),
            (" Toallas femeninas",12),
            (" Algodon",12),
            (" Tinte para el cabello",12),
            (" Biberones",12),
            (" Talco",12),
            (" Cepillo de dientes",12),
            (" Shampoo ",12),
            (" Acondicionador",12),
            (" Cotonetes",12),
            (" Rastrillos",12),
            (" Crema corporal",12),
            (" Crema facial",12),
            (" Papel higienico",12),
            (" Crema para afeitar",12),
            (" Pañuelos faciales",12),
            (" Dentifricos",12),
            (" Pañuelos desechables",12),
            (" Desodorantes en barra",12),
            (" Desodorantes en aerosol",12),
            (" Maquillaje",12),
            (" Enjuague bucal",12),
            (" Lubricantes para labios",12),
            (" Gel",12),
            (" Gel spray",12),
            (" Locion hidratante",12),
            (" Jabones corporales",12),
            (" Jabones de tocador",12),
            (" Suavizante de telas",13),
            (" acido muriatico",13),
            (" Sosa caustica",13),
            (" Aluminio",13),
            (" Pilas",13),
            (" Shampoo para ropa",13),
            (" Servilletas",13),
            (" Servitoallas",13),
            (" Aromatizantes",13),
            (" Cera para automovil",13),
            (" Cera para calzados",13),
            (" Pastillas sanitarias",13),
            (" Limpiadores liquidos",13),
            (" Limpiadores para pisos",13),
            (" Jabon de barra",13),
            (" Cerillos",13),
            (" Cloro",13),
            (" Blanqueador",13),
            (" Cloro para ropa",13),
            (" Insecticidas",13),
            (" Fibras limpiadoras",13),
            (" Desinfectantes",13),
            (" Detergentes para trastes",13),
            (" Detergente para ropa",13),
            (" Veladoras",14),
            (" Velas",14),
            (" Cepillo de plastico",14),
            (" Vasos desechables",14),
            (" Cinta adhesiva",14),
            (" Cucharas de plastico",14),
            (" Escobas",14),
            (" Trapeadores",14),
            (" Mechudos",14),
            (" Trampas para ratas",14),
            (" Tenedores de plastico",14),
            (" Extensiones",14),
            (" Multicontacto",14),
            (" Recogedor de metal",14),
            (" plastico",14),
            (" Popotes",14),
            (" Platos desechables",14),
            (" Focos",14),
            (" Fusibles",14),
            (" Jergas",14),
            (" franelas",14),
            (" Matamoscas",14),
            (" Pegamento",14),
            (" Mecate",14),
            (" cuerda",14),
            (" Tarjetas telefonicas",15),
            (" Recargas moviles",15),
            (" Hielo",15),
            (" Cigarros",15);


